spring:
  application:
    name: CheckinStatistics

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zkj
    username: root
    password: 123456

file:
  template:
    path: /Users/mojie/Desktop/daka  # 测试环境使用测试资源目录

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    session:
      #      cookie:
      #        max-age: 5s
      #      ?????s ???????60???????
      timeout: 2592000

# ??????
knife4j:
  enable: true
  openapi:
    title: "document"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.atyichen.checkinstatistics.excel.controller